version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
